#!/bin/bash

# 2023

m=`echo $1 | cut -d '_' -f1`
s=`echo $1 | cut -d '_' -f2`
pair=$1
outdir='RSLCRS'
mkdir -p $outdir
mkdir -p $outdir/$s
rslcdir=`pwd`/RSLC
mpar=$rslcdir/$m/$m.rslc.par
mslc=$rslcdir/$m/$m.rslc
spar=$rslcdir/$s/$s.rslc.par
sslc=$rslcdir/$s/$s.rslc
mmli=$rslcdir/$m/$m.rslc.mli.par
smli=$rslcdir/$s/$s.rslc.mli.par

SLC_interp_lt_ScanSAR tab/${s}R_tab $spar tab/${m}R_tab $mpar OFF/$pair/offsets.filtered.lut $mmli $smli OFF/$pair/tracking.off tab/20230210rsR_tab $outdir/$s/$s.rlsc $outdir/$s/$s.rlsc.par - 6 $outdir/$s/

cd $outdir/$s; chmod 777 *
echo $s.rslc $s.rslc.par $s.rslc.mli $s.rslc.mli.par
multi_look $s.rslc $s.rslc.par $s.rslc.mli $s.rslc.mli.par 20 4
cd ../..


echo $pair >ifg.list

if [ ! -d IFG/${m}_${s}.orig ]; then
 cd IFG; mv $m'_'$s $m'_'$s.orig; mkdir $m'_'$s; cd ../
fi


if [ ! -d RSLC/${s}.orig ]; then
 cd RSLC; mv $s $s.orig; ln -s ../$outdir/$s; cd ../
fi

mkdir -p log
LiCSAR_03_mk_ifgs.py -d . -i ifg.list -a 4 -r 20



